---
title: "Model Analysis"
author: "Polyphony J. Bruna"
date: "2024-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(lmerTest)
library(patchwork)
```

# Helper functions

```{r}
bin_series <- function(series, bin_size){
  series_length <- length(series)
  run_off <- series_length %% bin_size
  
  if(run_off > 0){
    series <- series[1:(series_length - run_off)]
  }
  
  series_binned <- sapply(seq(1, length(series), by = bin_size), 
                          function(k) mean(series[k:(k + bin_size - 1)]))
  return(series_binned)
}
```

# Replication figures

```{r}
data_2d <- read_csv("data/rep_over_time.csv") %>%
  group_by(run) %>%
  mutate(time = row_number())
```

```{r}
binned_data_2d <- setNames(data.frame(matrix(ncol = length(colnames(data_2d)), nrow = 0)), colnames(data_2d))

for(i in 1:max(data_2d$run)){
  run_data <- data_2d %>% filter(run == i)
  
  temp_df <- data.frame(
    cost = bin_series(run_data$cost, bin_size=250),
    cond_ent = bin_series(run_data$cond_ent, bin_size=250),
    sig_ent = bin_series(run_data$sig_ent, bin_size=250),
    run = i
  )
  
  binned_data_2d <- rbind(binned_data_2d, temp_df)
}

binned_data_2d <- binned_data_2d %>%
  group_by(run) %>%
  mutate(time = row_number())
```

```{r}
avg_data_2d <- data_2d %>%
  pivot_longer(cols = !c(run, time), names_to = "metric", values_to = "value") %>%
  group_by(metric, time) %>%
  summarize(m = mean(value), se = sd(value) / sqrt(n())) %>%
  filter(!is.na(se))
```

```{r}
avg_data_2d$metric <- factor(avg_data_2d$metric,
                             levels = c("sig_ent", "cost", "cond_ent"),
                             labels = c("Hn(S)", "Weighted Average", "Hm(R|S)"))

rep_over_time <- ggplot(avg_data_2d, aes(x = time, y = m, linetype = metric)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  labs(title = expression(lambda ~ " = 0.41"), x = "Time (1 unit = 250 timesteps)", y = "Value", linetype = "Measure") +
  theme_bw() +
  theme(axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))
```

```{r}
lambda_data <- read_csv("data/replication.csv") %>%
  pivot_longer(cols = !c(lambda), names_to = "metric", values_to = "value") %>%
  group_by(lambda, metric) %>%
  summarize(m = mean(value), se = sd(value) / sqrt(n()))
```

```{r}
rep_mi <- ggplot(lambda_data %>% filter(metric == "mi"), aes(x = lambda, y = m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  geom_vline(xintercept = 0.41, linetype = "dotted") +
  labs(x = expression(lambda), y = bquote(I[n](S,R))) +
  scale_y_continuous(limits = c(0,1)) +
  theme_bw() +
  theme(axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))

rep_lex <- ggplot(lambda_data %>% filter(metric == "lexicon"), aes(x = lambda, y = m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  geom_vline(xintercept = 0.41, linetype = "dotted") +
  labs(x = expression(lambda), y = "L") +
  scale_y_continuous(limits = c(0,1)) +
  theme_bw() +
  theme(axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))
```

```{r}
(rep_mi + rep_lex) / rep_over_time

#ggsave(file = "figures/model/figure_2.pdf", height = 7)
# ggsave(file = "figures/model/figure_2.png", height = 7)
```


# 3D figures

```{r}
data_3d <- read_csv("data/3d_n=6_l=0.41.csv")
```

```{r}
binned_data_3d <- setNames(data.frame(matrix(ncol = length(colnames(data_3d)), nrow = 0)), colnames(data_3d))

for(i in 1:max(data_3d$run)){
  run_data <- data_3d %>% filter(run == i)
  
  temp_df <- data.frame(
    cost_over_time = bin_series(run_data$cost_over_time, bin_size=250),
    cond_entropy_over_time = bin_series(run_data$cond_entropy_over_time, bin_size=250),
    signal_entropy_over_time = bin_series(run_data$signal_entropy_over_time, bin_size=250),
    jsd_over_time = bin_series(run_data$jsd_over_time, bin_size=250),
    combined_entropy_over_time = bin_series(run_data$combined_entropy_over_time, bin_size=250),
    sparsity_over_time = bin_series(run_data$sparsity_over_time, bin_size=250),
    run = i
  )
  
  binned_data_3d <- rbind(binned_data_3d, temp_df)
}

binned_data_3d <- binned_data_3d %>%
  group_by(run) %>%
  mutate(time = row_number())
```

```{r}
avg_data_3d <- binned_data_3d %>%
  pivot_longer(cols = !c(run, time), names_to = "metric", values_to = "value") %>%
  group_by(metric, time) %>%
  summarize(m = mean(value), se = sd(value) / sqrt(n())) %>%
  filter(!is.na(se))
```

```{r}
cost <- ggplot(avg_data_3d %>% filter(metric == "cost_over_time"), aes(x = time, y = m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(expression(Omega(lambda))) +
  theme_bw() +
  theme(axis.title.x = element_blank())

cond_ent <- ggplot(avg_data_3d %>% filter(metric == "cond_entropy_over_time"), aes(x = time, y = m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(H[m]("R|S"[1],S[2]))) + # "Hm(R|S1,S2)"
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "none")

sig_ent <- ggplot(avg_data_3d %>% filter(metric == "signal_entropy_over_time"), aes(x = time, y = m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(H[n](S[1],S[2]))) + # "Hn(S1,S2)"
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw()

cost / cond_ent / sig_ent

# ggsave(file = "figures/model/3d_cost.png", height = 7)
```

```{r}
ent <- ggplot(avg_data_3d %>% filter(metric == "combined_entropy_over_time"), aes(x=time, y=m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(H[n](S[1]+S[2]))) + 
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))

jsd <- ggplot(avg_data_3d %>% filter(metric == "jsd_over_time"), aes(x=time, y=m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(JSD(S[1],S[2]))) +
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw() +
  theme(axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))

ent / jsd

# ggsave(file = "figures/model/figure_3.pdf", height = 12)
# ggsave(file = "figures/model/figure_3.png", height = 12)
```

# 4D figures

```{r}
data <- read_csv("data/4d_n=6_l=0.6.csv")
```

```{r}
for(i in 1:4){
  batch <- read_csv(paste0("data/additional_runs_02_10/batch", i, "_4d_n=6_l=0.6.csv")) %>%
    mutate(run = run + (10*i))
  
  data <- rbind(data, batch)
}
```


```{r}
binned_data <- setNames(data.frame(matrix(ncol = length(colnames(data)), nrow = 0)), colnames(data))

for(i in 1:max(data$run)){
  run_data <- data %>% filter(run == i)
  
  temp_df <- data.frame(
    s1_cost_over_time = bin_series(run_data$s1_cost_over_time, bin_size=250),
    s2_cost_over_time = bin_series(run_data$s2_cost_over_time, bin_size=250),
    s1_cond_entropy_over_time = bin_series(run_data$s1_cond_entropy_over_time, bin_size=250),
    s2_cond_entropy_over_time = bin_series(run_data$s2_cond_entropy_over_time, bin_size=250),
    signal_entropy_over_time = bin_series(run_data$signal_entropy_over_time, bin_size=250),
    jsd_over_time = bin_series(run_data$jsd_over_time, bin_size=250),
    ref_align_mi = bin_series(run_data$ref_align_mi, bin_size=250),
    combined_entropy_over_time = bin_series(run_data$combined_entropy_over_time, bin_size=250),
    sparsity_over_time = bin_series(run_data$sparsity_over_time, bin_size=250),
    run = i
  )
  
  binned_data <- rbind(binned_data, temp_df)
}

binned_data <- binned_data %>%
  group_by(run) %>%
  mutate(time = row_number())
```

```{r}
avg_data <- binned_data %>%
  pivot_longer(cols = !c(run, time), names_to = "metric", values_to = "value") %>%
  group_by(metric, time) %>%
  summarize(m = mean(value), se = sd(value) / sqrt(n())) %>%
  filter(!is.na(se))
```

```{r}
cost_plot <- avg_data %>%
  filter(metric %in% c("s1_cost_over_time", "s2_cost_over_time",
                       "s1_cond_entropy_over_time", "s2_cond_entropy_over_time")) %>%
  mutate(Speaker = case_when(str_detect(metric, "1") ~ "S1", T ~ "S2"),
         metric = case_when(str_detect(metric, "cost") ~ "Cost", T ~ "H(R|S1,S2)"))

cost <- ggplot(cost_plot %>% filter(metric == "Cost"), aes(x = time, y = m, linetype = Speaker)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(expression(Omega(lambda))) +
  theme_bw() +
  theme(axis.title.x = element_blank())

cond_ent <- ggplot(cost_plot %>% filter(metric == "H(R|S1,S2)"), aes(x = time, y = m, linetype = Speaker)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(H[m]("R|S"[1],S[2]))) +
  theme_bw() +
  theme(axis.title.x = element_blank(),
        legend.position = "none")

sig_ent <- ggplot(avg_data %>% filter(metric == "signal_entropy_over_time"), aes(x = time, y = m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(H[n](S[1],S[2]))) +
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw()

cost / cond_ent / sig_ent

# ggsave(file = "figures/model/4d_cost.png", height = 7)
```

```{r}
mi <- ggplot(avg_data %>% filter(metric == "ref_align_mi"), aes(x=time, y=m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(I[n](R[1],R[2]))) +
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.y=element_text(size=11))

ent <- ggplot(avg_data %>% filter(metric == "combined_entropy_over_time"), aes(x=time, y=m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(H[n](S[1]+S[2]))) +
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw() +
  theme(axis.title.x=element_blank(),
        axis.text.y=element_text(size=11))

jsd <- ggplot(avg_data %>% filter(metric == "jsd_over_time"), aes(x=time, y=m)) +
  geom_path() +
  geom_ribbon(aes(ymin = m - se, ymax = m + se), alpha = 0.3) +
  ylab(bquote(JSD(S[1],S[2]))) +
  xlab("Time (1 unit = 250 timesteps)") +
  theme_bw() +
  theme(axis.text.x=element_text(size=11),
        axis.text.y=element_text(size=11))

mi / ent / jsd

# ggsave(file = "figures/model/figure_4.pdf", height = 12)
# ggsave(file = "figures/model/figure_4.png", height = 12)
```

# Inferential tests

```{r}
ggplot(binned_data, aes(x=time, y=ref_align_mi)) +
  facet_wrap(~run) +
  geom_path()

ggplot(binned_data, aes(x=time, y=combined_entropy_over_time)) +
  facet_wrap(~run) +
  geom_path()

ggplot(binned_data, aes(x=time, y=jsd_over_time)) +
  facet_wrap(~run) +
  geom_path()
```

```{r}
ggplot(binned_data, aes(x=combined_entropy_over_time, y=ref_align_mi)) +
  facet_wrap(~run) +
  geom_point(alpha = 0.1, size = 0.1)

ggplot(binned_data, aes(x=jsd_over_time, y=ref_align_mi)) +
  facet_wrap(~run) +
  geom_point(alpha = 0.1, size = 0.1)

ggplot(binned_data, aes(x=jsd_over_time, y=combined_entropy_over_time)) +
  facet_wrap(~run) +
  geom_point(alpha = 0.1, size = 0.1)
```

```{r}
m1_df <- avg_data %>%
  filter(metric %in% c("combined_entropy_over_time", "ref_align_mi")) %>%
  select(!se) %>%
  pivot_wider(names_from = metric, values_from = m)

ggplot(m1_df, aes(x=combined_entropy_over_time, y=ref_align_mi)) +
  geom_point(alpha = 0.1, size = 0.1) +
  xlab("H(S1+S2)") +
  ylab("MI(S1,S2)") +
  theme_bw()
```

```{r}
summary(lm(ref_align_mi ~ combined_entropy_over_time, data = m1_df))
```

```{r}
cov(m1_df$combined_entropy_over_time, m1_df$ref_align_mi)
cor(m1_df$combined_entropy_over_time, m1_df$ref_align_mi)
```


```{r}
m2_df <- avg_data %>%
  filter(metric %in% c("jsd_over_time", "ref_align_mi")) %>%
  select(!se) %>%
  pivot_wider(names_from = metric, values_from = m)

ggplot(m2_df, aes(x=jsd_over_time, y=ref_align_mi)) +
  geom_point(alpha = 0.1, size = 0.1) +
  xlab("JSD(S1,S2)") +
  ylab("MI(S1,S2)") +
  theme_bw()
```

```{r}
summary(lm(ref_align_mi ~ jsd_over_time, data = m2_df))
```
